# Generated by Django 2.1.7 on 2019-02-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaritem',
            name='time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
